[package]
name = "cosmic-applet-ime"
version = "1.9.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Generic COSMIC panel applet for org.inputmethod.Control1 engines"

[[bin]]
name = "cosmic-applet-ime"
path = "src/main.rs"

[dependencies]
cosmic-comp-config = { git = "https://github.com/rano-oss/cosmic-comp", branch = "experimental/xx-im-preedit-start" }
futures.workspace = true
ime-control = { path = "../ime-control" }
libcosmic.workspace = true
tokio.workspace = true
tracing-log.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
zbus.workspace = true
